[package]
name = "nonos-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
sysinfo = "0.30"
crossterm = "0.27"
tui = "0.19"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
colored = "2.0"
